from . import applicant_college_list
from . import share_applicant_data
from . import hr_applicant
from . import hr_recruitment_assessment
from . import hr_recruitment_industry
from . import hr_recruitment_hobbies
from . import applicant_project
from . import applicant_certificates
from . import applicant_employment
from . import hr_employee
from . import hr_recruitment_stages
from . import res_partner
from . import companies_requests
from . import company_request_wizard
from . import res_users
from . import college_users
from . import company_users
from . import hr_job
from . import user
from . import hr_recruitment_degree_type
from . import hr_talents
from . import res_company
from . import crm_lead
from . import applicants_share_wizard