{
    'name': 'G-Talent Pro customization',
    'version': '13.0.20',
    'category': 'Website',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'http://www.pragtech.co.in',
    'summary': 'The module will add applicant related data and will customize the complete flow of recruitment process',
    'depends': ['base','sale','crm','hr','hr_recruitment','account','hr_skills','mail','contacts', 'website_hr_recruitment','website_crm','mass_mailing','survey'],
    'data': [
        'security/ir.model.access.csv',
        'security/gtalentpro_security.xml',
        'views/applicant_share_wizard.xml',
        'data/website_data.xml',
        'views/share_data.xml',
        'views/company_request_wizard.xml',
#         'views/res_company_view.xml',
        'views/hr_applicant_view.xml',
        'views/hr_applicant_assessment.xml',
        'views/hr_applicant_industry_view.xml',
        'views/project_list_view.xml',
        'views/applicant_employment.xml',
        'views/hr_employee_view.xml',
        'views/connect_request_template.xml',
        'views/hr_stages_view.xml',
        'views/stage_data.xml',
        'views/connect_request_template.xml',
        'views/res_partner_view.xml',
        'views/college_users_view.xml',
        'views/assets.xml',
        'views/company_users_view.xml',
        'views/employer_user_views.xml',
        'views/companies_requests_view.xml',
        'views/assessment_data.xml',
        'views/hr_job_view.xml',
        'views/user_view.xml',
        'views/job_description_template.xml',
        'views/applicant_profile.xml',
        'views/submit_form_template.xml',
        'views/logged_in_template.xml',
        'views/job.xml',
        'views/job_description_page.xml',
        'views/hr_degree_type.xml',
        'views/talents_view.xml',
        'views/auth_signup.xml',
#         'views/hr_talents_view.xml',
        'views/footer.xml',
#         'views/company_view.xml'
        'views/profile_page.xml',
        'views/inherit_mail_message_view.xml',
        'views/inherit_contactus.xml',
        'views/portal_layout.xml',
    ],
    'currency': 'USD',
    'license': 'OPL-1',
    'installable': True,
    'application': False,
    'auto_install': False,
    }
